[package]
name = "harborlookout-storage"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
harborlookout-contracts = { path = "../contracts" }
harborlookout-domain = { path = "../domain" }
rusqlite.workspace = true
serde_json.workspace = true